{% set name = "hopcroftkarp" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28a7887db81ad995ccd36a1b5164a4c542b16d2781e8c49334dc9d141968c0e7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - hopcroftkarp

about:
  home: https://github.com/sofiatolaosebikan/hopcroftkarp
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'a module to find a maximum matching in bipartite graphs'

extra:
  recipe-maintainers:
    - asmeurer
    - henrik227
