travis:
  secure:
    BINSTAR_TOKEN: LPbcr5uFFej6FxLzGKo8GmSbc/doUPsagWHRs3Qu/Oqt9DWXC/BtDEcNVQxQZpH9z5Ib9+Kee3DrNdUg+h2yzS0P1Ax3YXbfbStHxkhzue1OgkJUpHTQH+lB1tr4nrLjYtfM+bhU+SHJ6IC38hshIigzhniLYrVxen5QfC+KI5rr8SEBDzYiTLjeDOU4bVvShDTN5BkR8kkCZaRSVf+GtzClVPKwDp0UoJ7zooHM7Lw2PfHJmQbQbMFBta/vd5tKCYclygqhqAWWdnYxbtujRALvRTBbdsWEyXx5ywIdzWRSsO7FXjBoYQgyPts2DTF3rm0hPWD4RyiU+nfj67D5aoXCwNM3cHh4m1gD9akspGdGzB4LQmInLYmcJQc8kxWqDnmgdWWeMqdXGD/S2rV9iymNa2D459bMM6V8toU7Y3cZgp0DoKIlX/lSP1nZjNc1ZB0oF1LIFD7XYjHw3kCcbE+NwV85QYQA0SydtIZfT9x3SdNhLWeJkUZJyIwFMnMWlagTKmNAw/Ary7l/EttHMvHGps1EfEqi5RRcdIvQJRXaNdcxC9+LBZMr53AgAkCW/bkr70KFo52WBTv0YhYpvH+dEZ4XOJDkH4hQXRYQsQTjkQvyQb9WYwSv8kUKAJHoMbF75tI8hKx2Pfo9zOksX7JwpSLfHVOy+1tNIpel0hY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
